version: '3.1'
services:
    postgresql:
        build:
            context: ./postgresql
        networks:
            - spring-boot-consume-api-service
    mysql:
        build:
            context: ./mysql
        networks:
            - spring-boot-consume-api-service 
    spring-boot:
        build:
            context: ./spring-boot
        ports:
            - 8080:8080
        networks:
            - spring-boot-consume-api-service  
        depends_on:
            - postgresql
    api-service:
        build:
            context: ./api-service
            ports:
                - 8081:8080
        networks:
            - spring-boot-consume-api-service  
        depends_on:
            - postgresql    
networks:
    spring-boot-consume-api-service: